version: '3'
services:
  db:
    image: mysql:5.7
    env_file: ./mysql.env
    environment: 
      - TZ=Asia/Tokyo
    ports:
      - '3306:3306'
    volumes:
      - ./db/mysql/conf:/etc/mysql/conf.d/:ro
      - ./db/mysqldata:/var/lib/mysql
    container_name: mysql_db
  web:
    image: nginx:latest
    container_name: "web"
    ports:
      - "80:80"
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
  app:
    build: .
    env_file: ./app.env
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    #command: yarn dev
    command: /bin/sh